site_name: Itia Wiki
site_url: https://avventureaditia.github.io/itia-wiki
site_description: La wiki ufficiale della regione di Itia
site_author: AvventureAdItia
repo_url: https://github.com/AvventureAdItia/itia-wiki
theme:
  name: material
  features:
  - content.tabls.links
  - content.tooltips
  favicon: img/items/poke-ball.png
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye
      name: Switch to light mode
nav:
- Home: index.md
- Ability Changes: ability_changes.md
- Pokemon:
  - 001 - Timolino: pokemon/001-timolino.md
  - 002 - Thymad: pokemon/002-thymad.md
  - 003 - Thybrave: pokemon/003-thybrave.md
  - 004 - Flammid: pokemon/004-flammid.md
  - 005 - Yulot: pokemon/005-yulot.md
  - 006 - Phyries: pokemon/006-phyries.md
  - 007 - Badaliz: pokemon/007-badaliz.md
  - 008 - Propellisk: pokemon/008-propellisk.md
  - 009 - Badalinci: pokemon/009-badalinci.md
  - 010 - Amath: pokemon/010-amath.md
  - 011 - Pecuru: pokemon/011-pecuru.md
  - 012 - Phegea: pokemon/012-phegea.md
  - 013 - Azuerla: pokemon/013-azuerla.md
  - 014 - Albeste: pokemon/014-albeste.md
  - 015 - Yawnouse: pokemon/015-yawnouse.md
  - 016 - Mousleep: pokemon/016-mousleep.md
  - 017 - Skitty Itia: pokemon/017-skitty-itia.md
  - 018 - Delcatty Itia: pokemon/018-delcatty-itia.md
  - 019 - Dresscatty: pokemon/019-dresscatty.md
  - 020 - Spoink Itia: pokemon/020-spoink-itia.md
  - 021 - Spiboarth: pokemon/021-spiboarth.md
  - 022 - Phantump Itia: pokemon/022-phantump-itia.md
  - 023 - Dumsnot: pokemon/023-dumsnot.md
  - 024 - Indrygard: pokemon/024-indrygard.md
  - 025 - Nixiro: pokemon/025-nixiro.md
  - 026 - Scipirock: pokemon/026-scipirock.md
  - 027 - Poliphant: pokemon/027-poliphant.md
  - 028 - Tendephant: pokemon/028-tendephant.md
  - 030 - Fromses: pokemon/030-fromses.md
  - 031 - Glaspirit: pokemon/031-glaspirit.md
  - 032 - Batcot: pokemon/032-batcot.md
  - 033 - Flakewing: pokemon/033-flakewing.md
  - 033 - Skulknam: pokemon/033-skulknam.md
  - 035 - Icyshblord: pokemon/035-icyshblord.md
  - 036 - Flocywerth: pokemon/036-flocywerth.md
  - 037 - Stakiles: pokemon/037-stakiles.md
  - 037 - Vesteam: pokemon/037-vesteam.md
  - 039 - Fember: pokemon/039-fember.md
  - 040 - Insolame: pokemon/040-insolame.md
  - 041 - Reclugma: pokemon/041-reclugma.md
  - 042 - Heatdoubt: pokemon/042-heatdoubt.md
  - 043 - Volchamber: pokemon/043-volchamber.md
  - 044 - Rhinocola: pokemon/044-rhinocola.md
  - 045 - Rhinostris: pokemon/045-rhinostris.md
  - 046 - Gondoval: pokemon/046-gondoval.md
  - 047 - Cryptidile: pokemon/047-cryptidile.md
  - 048 - Elusuchus: pokemon/048-elusuchus.md
  - 049 - Teetitan: pokemon/049-teetitan.md
  - 050 - Muskuma: pokemon/050-muskuma.md
  - 051 - Marsikane: pokemon/051-marsikane.md
  - 053 - Rupedola: pokemon/053-rupedola.md
  - 054 - Camuninfa: pokemon/054-camuninfa.md
  - 067 - Eelazzle: pokemon/067-eelazzle.md
- Routes: []
plugins:
- search:
    lang: en
markdown_extensions:
- admonition
- abbr
- attr_list
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- stylesheets/extra.css
