site_name: Itia Wiki
site_url: https://avventureaditia.github.io/itia-wiki
site_description: La wiki ufficiale della regione di Itia
site_author: AvventureAdItia
repo_url: https://github.com/AvventureAdItia/itia-wiki
theme:
  name: material
  features:
  - content.tabls.links
  - content.tooltips
  favicon: img/items/poke-ball.png
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye
      name: Switch to light mode
nav:
- Home: index.md
- Ability Changes: ability_changes.md
- Pokemon:
  - 001 - Timolino: pokemon/001-timolino.md
  - 002 - Thymad: pokemon/002-thymad.md
  - 003 - Thybrave: pokemon/003-thybrave.md
  - 004 - Flammid: pokemon/004-flammid.md
  - 005 - Yulot: pokemon/005-yulot.md
  - 006 - Phyries: pokemon/006-phyries.md
  - 007 - Badaliz: pokemon/007-badaliz.md
  - 008 - Propellisk: pokemon/008-propellisk.md
  - 009 - Badalinci: pokemon/009-badalinci.md
  - 010 - Amath: pokemon/010-amath.md
  - 011 - Pecuru: pokemon/011-pecuru.md
  - 012 - Phegea: pokemon/012-phegea.md
  - 013 - Azuerla: pokemon/013-azuerla.md
  - 014 - Albeste: pokemon/014-albeste.md
  - 015 - Yawnouse: pokemon/015-yawnouse.md
  - 016 - Mousleep: pokemon/016-mousleep.md
  - 017 - Skitty Itia: pokemon/017-skitty-itia.md
  - 018 - Delcatty Itia: pokemon/018-delcatty-itia.md
  - 019 - Dresscatty: pokemon/019-dresscatty.md
  - 020 - Spoink Itia: pokemon/020-spoink-itia.md
  - 021 - Spiboarth: pokemon/021-spiboarth.md
  - 022 - Phantump Itia: pokemon/022-phantump-itia.md
  - 023 - Dumsnot: pokemon/023-dumsnot.md
  - 024 - Indrygard: pokemon/024-indrygard.md
  - 025 - Nixiro: pokemon/025-nixiro.md
  - 026 - Scipirock: pokemon/026-scipirock.md
  - 027 - Poliphant: pokemon/027-poliphant.md
  - 028 - Tendephant: pokemon/028-tendephant.md
  - 029 - Mystrauk: pokemon/029-mystrauk.md
  - 030 - Easplosion: pokemon/030-easplosion.md
  - 031 - Fromses: pokemon/031-fromses.md
  - 032 - Glaspirit: pokemon/032-glaspirit.md
  - 033 - Batcot: pokemon/033-batcot.md
  - 034 - Flakewing: pokemon/034-flakewing.md
  - 035 - Skulknam: pokemon/035-skulknam.md
  - 036 - Icyshblord: pokemon/036-icyshblord.md
  - 037 - Flocywerth: pokemon/037-flocywerth.md
  - 038 - Stakiles: pokemon/038-stakiles.md
  - 038 - Vesteam: pokemon/038-vesteam.md
  - 040 - Fember: pokemon/040-fember.md
  - 041 - Insolame: pokemon/041-insolame.md
  - 042 - Reclugma: pokemon/042-reclugma.md
  - 043 - Heatdoubt: pokemon/043-heatdoubt.md
  - 044 - Volchamber: pokemon/044-volchamber.md
  - 045 - Rhinocola: pokemon/045-rhinocola.md
  - 046 - Rhinostris: pokemon/046-rhinostris.md
  - 047 - Gondoval: pokemon/047-gondoval.md
  - 048 - Cryptidile: pokemon/048-cryptidile.md
  - 049 - Elusuchus: pokemon/049-elusuchus.md
  - 050 - Teetitan: pokemon/050-teetitan.md
  - 051 - Muskuma: pokemon/051-muskuma.md
  - 052 - Marsikane: pokemon/052-marsikane.md
  - 053 - Staly: pokemon/053-staly.md
  - 054 - Rupedola: pokemon/054-rupedola.md
  - 055 - Camuninfa: pokemon/055-camuninfa.md
  - 056 - Voluva: pokemon/056-voluva.md
  - 057 - Uvanity: pokemon/057-uvanity.md
  - 058 - Mullitos: pokemon/058-mullitos.md
  - 059 - Nuraghimin: pokemon/059-nuraghimin.md
  - 060 - Frogtry: pokemon/060-frogtry.md
  - 061 - Galvtoadur: pokemon/061-galvtoadur.md
  - 062 - Sparkynx: pokemon/062-sparkynx.md
  - 063 - Rotom Squillo: pokemon/063-rotom-squillo.md
  - 063 - Lighynx: pokemon/063-lighynx.md
  - 064 - Rotom Squillo: pokemon/064-rotom-squillo.md
  - 065 - Gladeon: pokemon/065-gladeon.md
  - 066 - Vipeon: pokemon/066-vipeon.md
  - 067 - Baundeon: pokemon/067-baundeon.md
  - 068 - Eelandit: pokemon/068-eelandit.md
  - 069 - Eelazzle: pokemon/069-eelazzle.md
  - 070 - Swarmub: pokemon/070-swarmub.md
  - 071 - Piloswarm: pokemon/071-piloswarm.md
  - 072 - Mamoswarm: pokemon/072-mamoswarm.md
  - 073 - Bagle: pokemon/073-bagle.md
  - 074 - Shielgle: pokemon/074-shielgle.md
  - 075 - Glemence: pokemon/075-glemence.md
  - 076 - Ghostmare: pokemon/076-ghostmare.md
  - 077 - Panpup: pokemon/077-panpup.md
  - 078 - Pangher: pokemon/078-pangher.md
  - 079 - Strigowl: pokemon/079-strigowl.md
  - 080 - Ozbell: pokemon/080-ozbell.md
  - 081 - Apipomuf: pokemon/081-apipomuf.md
  - 082 - Dracalier: pokemon/082-dracalier.md
  - 083 - Gravient: pokemon/083-gravient.md
  - 084 - Relicor: pokemon/084-relicor.md
  - 085 - Grimtune: pokemon/085-grimtune.md
  - 086 - Crisismear: pokemon/086-crisismear.md
- Routes: []
plugins:
- search:
    lang: en
markdown_extensions:
- admonition
- abbr
- attr_list
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- stylesheets/extra.css
